ssids:
	- name: "Rylan-Home"
		vlan: 30
		password: "REDACTED"
		security: wpa3
	- name: "Rylan-Guest"
		vlan: 1
		guest_policy: true
		client_isolation: true
		bandwidth_limit_down: 50
		bandwidth_limit_up: 10
